# Generated by Django 5.2.7 on 2025-10-11 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoActor', models.CharField(choices=[('ABO', 'Abogado'), ('CLI', 'Cliente'), ('ASI', 'Asistente')], max_length=5)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidoPaterno', models.CharField(max_length=80)),
                ('apellidoMaterno', models.CharField(blank=True, max_length=80)),
                ('ci', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.TextField(blank=True)),
                ('estadoActor', models.CharField(default='ACTIVO', max_length=20)),
                ('creadoEn', models.DateTimeField(auto_now_add=True)),
                ('actualizadoEn', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='actor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='abogado', serialize=False, to='actores.actor')),
                ('nroCredencial', models.CharField(max_length=50)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('estadoLicencia', models.CharField(default='VIGENTE', max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['estadoLicencia'], name='actores_abo_estadoL_8be88f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asistente', serialize=False, to='actores.actor')),
                ('area', models.CharField(blank=True, max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['area', 'cargo'], name='actores_asi_area_d5ce16_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cliente', serialize=False, to='actores.actor')),
                ('tipoCliente', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICO', 'Jurídico')], max_length=10)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tipoCliente'], name='actores_cli_tipoCli_775c13_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['tipoActor'], name='actores_act_tipoAct_40673f_idx'),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['estadoActor'], name='actores_act_estadoA_796f2e_idx'),
        ),
    ]
