# Generated by Django 5.2.7 on 2025-10-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='estadoActor',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20),
        ),
    ]
