# Generated by Django 5.2.7 on 2025-10-11 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProcesal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=200)),
                ('rutaDocumento', models.CharField(max_length=255)),
                ('tamano', models.FloatField(help_text='Tamaño en MB o KB')),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('palabraClave', models.CharField(blank=True, max_length=150)),
                ('fechaDoc', models.DateField(help_text='Fecha del documento (emisión o recepción)')),
                ('creadoEn', models.DateTimeField(auto_now_add=True)),
                ('actualizadoEn', models.DateTimeField(auto_now=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='casos.carpeta')),
                ('etapaProcesal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.etapaprocesal')),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroVersion', models.PositiveIntegerField()),
                ('rutaArchivo', models.CharField(max_length=255)),
                ('fechaCambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documentos.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fechaCambio'],
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['carpeta', 'estado'], name='documentos__carpeta_f2387b_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fechaDoc'], name='documentos__fechaDo_a17f22_idx'),
        ),
        migrations.AddIndex(
            model_name='versiondocumento',
            index=models.Index(fields=['documento', 'numeroVersion'], name='documentos__documen_e75e42_idx'),
        ),
        migrations.AddIndex(
            model_name='versiondocumento',
            index=models.Index(fields=['usuario'], name='documentos__usuario_2c01d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='versiondocumento',
            unique_together={('documento', 'numeroVersion')},
        ),
    ]
