# Generated by Django 5.2.7 on 2025-10-12 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actores', '0002_alter_actor_estadoactor'),
        ('casos', '0001_initial'),
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('modelo_openai', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('temperatura', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('contexto_sistema', models.TextField(default='Eres un asistente legal especializado en gestión documental. Ayudas a los usuarios a encontrar y analizar documentos, casos y actores del sistema. Siempre responde en español y de manera profesional.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración IA',
                'verbose_name_plural': 'Configuraciones IA',
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Asistente IA'), ('sistema', 'Sistema')], max_length=20)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('tokens_usados', models.IntegerField(blank=True, null=True)),
                ('tiempo_respuesta', models.FloatField(blank=True, null=True)),
                ('documentos_consultados', models.JSONField(blank=True, default=list)),
                ('entidades_extraidas', models.JSONField(blank=True, default=list)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.conversacion')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(max_length=50)),
                ('resultado', models.TextField(blank=True)),
                ('relevancia', models.FloatField(default=0.0)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actores.actor')),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casos.caso')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.documento')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_documentos', to='chat.mensaje')),
            ],
            options={
                'verbose_name': 'Consulta a Documento',
                'verbose_name_plural': 'Consultas a Documentos',
            },
        ),
    ]
