# Generated by Django 5.2.7 on 2025-10-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorol',
            name='fechaAsignacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
