# Generated by Django 5.2.7 on 2025-10-13 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_usuariorol_fechaasignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='login_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='userAgent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
