# Generated by Django 5.2.7 on 2025-10-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroCaso', models.CharField(max_length=50, unique=True)),
                ('tipoCaso', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(default='ABIERTO', max_length=20)),
                ('prioridad', models.CharField(default='MEDIA', max_length=20)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('creadoEn', models.DateTimeField(auto_now_add=True)),
                ('actualizadoEn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['estado', 'prioridad'], name='casos_caso_estado_29f25d_idx'), models.Index(fields=['fechaInicio'], name='casos_caso_fechaIn_89fae5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroExpediente', models.CharField(max_length=50)),
                ('estado', models.CharField(default='ABIERTO', max_length=20)),
                ('fechaCreacion', models.DateField()),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='casos.caso')),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('creadoEn', models.DateTimeField(auto_now_add=True)),
                ('actualizadoEn', models.DateTimeField(auto_now=True)),
                ('carpetaPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcarpetas', to='casos.carpeta')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='casos.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='ParteProcesal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolProcesal', models.CharField(choices=[('DEMANDANTE', 'Demandante'), ('DEMANDADO', 'Demandado'), ('TERCERO', 'Tercero')], max_length=20)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.caso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actores.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolEnEquipo', models.CharField(choices=[('RESPONSABLE', 'Responsable'), ('ASOCIADO', 'Asociado'), ('ASISTENTE', 'Asistente')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fechaAsignacion', models.DateField()),
                ('fechaSalida', models.DateField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actores.actor')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.caso')),
            ],
            options={
                'indexes': [models.Index(fields=['caso', 'rolEnEquipo'], name='casos_equip_caso_id_e6f215_idx'), models.Index(fields=['actor', 'caso'], name='casos_equip_actor_i_1f3820_idx')],
                'unique_together': {('actor', 'caso')},
            },
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['estado'], name='casos_exped_estado_04ebc0_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['fechaCreacion'], name='casos_exped_fechaCr_13e842_idx'),
        ),
        migrations.AddIndex(
            model_name='carpeta',
            index=models.Index(fields=['expediente', 'estado'], name='casos_carpe_expedie_897049_idx'),
        ),
        migrations.AddIndex(
            model_name='carpeta',
            index=models.Index(fields=['carpetaPadre'], name='casos_carpe_carpeta_8d2f87_idx'),
        ),
        migrations.AddIndex(
            model_name='parteprocesal',
            index=models.Index(fields=['caso', 'rolProcesal'], name='casos_parte_caso_id_931641_idx'),
        ),
        migrations.AddIndex(
            model_name='parteprocesal',
            index=models.Index(fields=['cliente', 'caso'], name='casos_parte_cliente_6ab0f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parteprocesal',
            unique_together={('cliente', 'caso')},
        ),
    ]
